name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: 'maven'
      
      - name: Build with Maven in Docker
        run: |
          docker run \
            -v $PWD:/src \
            -v $HOME/.m2:/root/.m2 \
            -e VAULT_TOKEN=${{ secrets.VAULT_TOKEN }} \
            moussavdb/build-java:lts